feat: flujo e2e
NHLGuerrero/aut-ui-playwright pull request #2
Opened 2022-11-12 02:41 UTC by NHLGuerrero

2022-11-13 23:27 UTC, car-vigo requested changes
Probaría añadir una clase que sea ProductDetail para que puedas abstraer la pantalla donde muestra el detalle del producto seleccionado y te permite añadir al carrito. 
Otra clase tendría que ser Cart.

2022-11-13 23:27 UTC, car-vigo commented on demoblaze/pages/addtocart-macbook-page.ts
> +export class AddTocartMacbookPage {
Tiene más sentido que la page sea Cart o ProductDetail, segun el enfoque que le quieras dar, así te permite añadir distintos elementos y no solo una mackbook.

2022-11-13 23:27 UTC, car-vigo commented on demoblaze/pages/addtocart-macbook-page.ts
> +        await this.page.goto('/prod.html?idp_=11');
Si la page es Cart este goto debería cambiarse, por ejemplo goto('/cart.html')
La url no debería llevar a un producto en particular.

2022-11-13 23:27 UTC, car-vigo commented on demoblaze/pages/addtocart-macbook-page.ts
> +    async checkTextMacbook(productName: string) {
El metodo podría llamarse checkProductName, para que aplique a cualquier producto y no solo a una mackbook

2022-11-13 23:27 UTC, car-vigo commented on demoblaze/pages/addtocart-macbook-page.ts
> +    async addtocartMacbook(){
Lo mismo para este, agrega valor el hecho de que el metodo esté parametrizado y pueda añadir cualquier producto

2022-11-14 13:44 UTC, car-vigo requested changes

2022-11-14 13:44 UTC, car-vigo commented on demoblaze/pages/cart-page.ts
> +        await expect(this.textMacBook).toHaveText(productName);
Este metodo solo funcionaria para el produycto MAckbook air, tal vez serpia mejor cambiar el selector por uno más generico, o utilizar un string parametizable. Por ejemplo
async checkProductName(productName: string) {}
        const productName = this.page.locator(`text=${productName}`)
        await this.itemRow.waitFor({ state: "visible" });
        await expect(productName).toHaveText(productName);

2022-11-14 13:44 UTC, car-vigo commented on demoblaze/pages/home-page.ts
> +        await expect(this.categorieLaptops).toHaveText(category);
Este metodo solo funciona con categoría laptops

2022-11-14 13:44 UTC, car-vigo commented on demoblaze/pages/product-detail-page.ts
> +        await expect(this.textMacbook).toHaveText(productName);
Este check tambien solo funciona para mackbook, que pasaría si le pasas otra cosa que no fuera Mackbook Air?

2022-11-16 20:48 UTC, NHLGuerrero commented on demoblaze/pages/cart-page.ts
> +    readonly productName: Locator;
Paso 1: elimino las propiedades anteriores y agrego la nueva.

2022-11-16 20:50 UTC, NHLGuerrero commented on demoblaze/pages/cart-page.ts
> +        const productName = page.locator(`text=${productName}`);
El error lo marca acá, me está diciendo que uso la variable de ambito del bloque "productName" antes de declararla.

Lo que no termino de entender es como va a hacer la relación el método con la propiedad.

2022-11-17 02:01 UTC, closed without merging